server:
  port: 4000
minio:
  url: http://ip:9000
  accessKey: minioadmin
  secretKey: minioadmin
#storage:
#  service:
#    type: minio
#spring:
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB