server:
  port: 4000
minio:
  url: http://ip:port
  accessKey: admin
  secretKey: pwd
#spring:
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB

